name: Deploy TqsftVpcStack

permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.

on:
 push:
   branches:
     - main
     - develop

jobs:
 deploy_lambda_stack:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "GitHubActions-DeployLayerStack"

     - name: Deploy TqsftVpcStack (via CDK)
       uses: youyo/aws-cdk-github-actions@v2
       env:
        VPC_CIDR: ${{ vars.VPC_CIDR }}
       with:
         cdk_subcommand: 'deploy'
         cdk_stack: 'TqsftVpcStack'
         cdk_args: '--require-approval never' 
         actions_comment: false